name: Client Query Notification
on:
  workflow_dispatch:
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Team
        run: echo "CLIENT QUERY: [Nombre]. Notifying team: [UsuarioGitHub], Colaborador1, Colaborador2."
